name = "MahjongTiles"
uuid = "4428f09d-fda0-4bc5-909e-74e028533219"
authors = ["Timothy Lin <32549553+tmthyln@users.noreply.github.com>"]
version = "1.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.6"
DataStructures = "0.18"
